CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);
    
CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML - LINGUAGEM DE MANIPULAÇÃO 
-- INSERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("EMAIL@EMAIL.COM","19999999999","123456789","LEO");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;

INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("louismigueldiasvalentim@gmail.com","19992001966","44817917806","Louis Miguel");

INSERT INTO CLIENTE (NOME,EMAIL, CPF,TELEFONE)
VALUES ("Louis", "louis@email.com", "19992001966","44817917806");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("MacBook M4", "Notebook	 Apple",4789.90,5);

SELECT * FROM PRODUTO;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("IPHONE 17","CELULAR APPLE",1200,10);

SELECT * FROM PRODUTO;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("IPHONE 13","CELULAR APPLE",3500,999);

SELECT * FROM PRODUTO;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("IPHONE 12","CELULAR APPLE",2300,999);

SELECT * FROM PRODUTO;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("IPHONE 14","CELULAR APPLE",4500,999);

SELECT * FROM PRODUTO;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;

-- INSERIR ALUGUEL
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-09-24","2025-10-01",7890,3,2);

SELECT * FROM ALUGUEL;
SELECT * FROM PRODUTO;
-- ATUALIZAR UM REGISTRO (UPDATE)
UPDATE PRODUTO
SET PRECO = 3500
WHERE PRODUTO_ID = 1;

UPDATE PRODUTO
SET PRECO = 1200
WHERE PRODUTO_ID = 6;

UPDATE PRODUTO
SET PRECO = 3500
WHERE PRODUTO_ID = 5;

UPDATE PRODUTO
SET PRECO = 5000
WHERE PRODUTO_ID = 10;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 1200
WHERE PRODUTO_ID = 2;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 4500
WHERE PRODUTO_ID = 3;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 6500
WHERE PRODUTO_ID = 4;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 7000
WHERE PRODUTO_ID = 7;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 1000
WHERE PRODUTO_ID = 10;

UPDATE CLIENTE
SET EMAIL = "louismigueldiasvalentim@gmail.com"
WHERE CLIENTE_ID = 1;

UPDATE CLIENTE
SET EMAIL = "reginadiasvalentim73@gmail.com"
WHERE CLIENTE_ID = 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-10-10"
WHERE ALUGUEL_ID= 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-09-05"
WHERE ALUGUEL_ID= 3;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-01-18"
WHERE ALUGUEL_ID= 4;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-03-09"
WHERE ALUGUEL_ID= 5;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-11-11"
WHERE ALUGUEL_ID= 6;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-06-05"
WHERE ALUGUEL_ID= 7;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-15"
WHERE ALUGUEL_ID= 8;

-- APAGAR UM REGISTRO (DELETE)
DELETE FROM CLIENTE 
WHERE       CLIENTE_ID = 1;

DELETE FROM ALUGUEL
WHERE       ALUGUEL_ID = 3;