CREATE DATABASE BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QTD_MUSICA VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    PRODUTOR VARCHAR(255) NOT NULL,
    FK_CPF_ARTISTA VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA (CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR(255) NOT NULL,
    DATA_FAIXA DATE NOT NULL,
    DURACAO VARCHAR(255) NOT NULL,
    VISUALIZACAO VARCHAR(255) NOT NULL,
    FK_ID_ALBUM INTEGER,
    FK_ID_GENERO INTEGER,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM (ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO (ID)
);