CREATE DATABASE BD_BIBLIOTECA_DIGITAL;
USE BD_BIBLIOTECA_DIGITAL;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR (15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    FOTO BLOB NOT NULL,
    GENERO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR (15) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    CONTA VARCHAR (255) NOT NULL,
    CARTAO VARCHAR (255) NOT NULL,
    GENERO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    FOTO BLOB NOT NULL,
    DESCRICAO VARCHAR (255),
    CATEGORIA VARCHAR (255) NOT NULL,
    COMPRA VARCHAR (255) NOT NULL,
    TRADUCAO VARCHAR(500),
    FK_CPF_AUTOR VARCHAR(15),
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ACESSAR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER,
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FK_CPF_LEITOR VARCHAR (15),
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);