CREATE DATABASE BD_CONSULTAS_MEDICAS;
USE BD_CONSULTAS_MEDICAS;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR (20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR (255) NOT NULL,
    INFORMACOES VARCHAR (255) NOT NULL,
    ESPECIALIZACAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR (15) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    MOTIVO VARCHAR (500) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    HORARIO VARCHAR (50) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    CARACTERISTICAS VARCHAR (255) NOT NULL,
    ENDERECO VARCHAR (255) NOT NULL,
    FK_CRM_MEDICO VARCHAR (20),
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FK_CPF_PACIENTE VARCHAR (15),
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);
