CREATE DATABASE BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;
	
CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD_PRODUTO INTEGER NOT NULL,
    DATA_PRODUTO DATE,
    PRECO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_ID_PRODUTO INTEGER,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO (ID)
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CNPJ_FORNECEDOR VARCHAR(20) NOT NULL,
    FK_ID_PRODUTO INTEGER,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR (CNPJ),
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO (ID)
);