CREATE DATABASE IF NOT EXISTS BD_ENQUETES_2ANO;
USE BD_ENQUETES_2ANO;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AEREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AEREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO", "CASADO", "DIVORCIADO", "VIUVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MEDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
	ENQ_DATA_FINAL DATE,
	ENQ_DATA_INICIAL DATE NOT NULL,
	ENQ_DESCRICAO VARCHAR(500) NOT NULL,
	ENQ_NOME VARCHAR(255) NOT NULL,
	FK_USU_CODIGO INTEGER NOT NULL,
	PRIMARY KEY (ENQ_CODIGO),
	FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETES(
	URE_CODIGO INTEGER AUTO_INCREMENT,
	URE_DATA DATE NOT NULL,
	FK_USU_CODIGO INTEGER,
	FK_ENQ_CODIGO INTEGER,
	PRIMARY KEY (URE_CODIGO),
	FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
	FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTA(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(2) NOT NULL,
    FK_PER_CODIGO INTEGER,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (USU_LOGIN, USU_AEREA_ATUACAO,USU_PROFISSAO,USU_AEREA_FORMACAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","LOUIS_019","REPRESENTANTE_VENDAS","VENDEDOR","CIENCIA DO ESPORTE","2007-09-05","SOLTEIRO","SP","MEDIO","LOUISMIGUEL@GMAIL.COM","GLOUIS123","LOUIS_123");

INSERT INTO USUARIO (USU_LOGIN, USU_AEREA_ATUACAO,USU_PROFISSAO,USU_AEREA_FORMACAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","LOUIS_019","REPRESENTANTE_VENDAS","VENDEDOR","CIENCIA DO ESPORTE","2007-09-05","SOLTEIRO","SP","MEDIO","LOUISMIGUEL@GMAIL.COM","GLOUIS123","LOUIS_123");

INSERT INTO USUARIO (USU_LOGIN, USU_AEREA_ATUACAO,USU_PROFISSAO,USU_AEREA_FORMACAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","LOUIS_019","REPRESENTANTE_VENDAS","VENDEDOR","CIENCIA DO ESPORTE","2007-09-05","SOLTEIRO","SP","MEDIO","LOUISMIGUEL@GMAIL.COM","GLOUIS123","LOUIS_123");

SELECT * FROM USUARIO;

INSERT INTO ENQUETE ( ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-01","2025-10-24", "2025-08-01","ENQUETE SOBRE GRAMA","GRAMA NATURAL", "FALSA", "3");

INSERT INTO ENQUETE ( ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-01","2025-10-24", "2025-08-01","ENQUETE SOBRE GRAMA","GRAMA NATURAL", "FALSA", "3");

INSERT INTO ENQUETE ( ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-01","2025-10-24", "2025-08-01","ENQUETE SOBRE GRAMA","GRAMA NATURAL", "FALSA", "3");

SELECT * FROM ENQUETE;

INSERT INTO USUARIO_RESPONDE_ENQUETE ( URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "3", "2");

INSERT INTO USUARIO_RESPONDE_ENQUETE ( URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "3", "2");

INSERT INTO USUARIO_RESPONDE_ENQUETE ( URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", "3", "2");

SELECT * FROM  USUARIO_RESPONDE_ENQUETE;

INSERT INTO PERGUNTA ( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("QUAL ESPORTE TEM MAIS JOGADORES");

INSERT INTO PERGUNTA ( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("QUAL ESPORTE TEM MENOS JOGADORES");

INSERT INTO PERGUNTA ( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("QUAL ESPORTE TEM 1 JOGADOR");

SELECT * FROM PERGUNTA;

INSERT INTO RESPOSTAS ( RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("A-FUTEBOL", "A", "1"); 

INSERT INTO RESPOSTAS ( RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("B-BOXE", "B","2");

SELECT * FROM RESPOSTAS;