CREATE DATABASE BD_GERENCIAR_PROJETOS;
USE BD_GERENCIAR_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    INDENTIDADE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255)NOT NULL,
    IDADE VARCHAR(5) NOT NULL,
    DATA_NASCIMENTO VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(14) NOT NULL,
    FK_ID_PROJETO INTEGER,
    FK_CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO (ID),
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF)
);