CREATE DATABASE BD_RES_HOTEL;
USE BD_RES_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(5),
    FOTO VARCHAR(255) NOT NULL,
    FK_CNPJ_HOTEL VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_CNPJ_HOTEL) REFERENCES HOTEL (CNPJ)
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_QUARTO INTEGER,
    FK_CPF_HOSPEDE VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_QUARTO) REFERENCES QUARTO (ID),
    FOREIGN KEY (FK_CPF_HOSPEDE) REFERENCES HOSPEDE (CPF)
);