CREATE DATABASE BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE VARCHAR(5) NOT NULL,
    PASSAPORTE VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(5),
    VALOR DOUBLE NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FK_CPF_PASSAGEIRO VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO (CPF)
);

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    COMPANHIA_AEREA VARCHAR(255) NOT NULL,
    LOCAL_VOO VARCHAR(255) NOT NULL,
    FK_ID_ASSENTO INTEGER,
    FOREIGN KEY (FK_ID_ASSENTO) REFERENCES ASSENTO (ID)
);