CREATE DATABASE BD_STREAM_VIDEO;
USE BD_STREAM_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE VARCHAR(5) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEMPO VARCHAR(255) NOT NULL,
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA (ID)
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACAO VARCHAR(50) NOT NULL,
    FK_ID_VIDEO INTEGER,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO (ID)
);
